export const countryData = [
    { id: 1, label: "Afghanistan", value: "AF" },
    { id: 2, label: "Albania", value: "AL" },
    { id: 3, label: "Algeria", value: "DZ" },
    { id: 4, label: "American Samoa", value: "AS" },
    { id: 5, label: "Andorra", value: "AD" },
    { id: 6, label: "Angola", value: "AO" },
    { id: 7, label: "Anguilla", value: "AI" },
    { id: 8, label: "Antarctica", value: "AQ" },
    { id: 9, label: "Antigua and Barbuda", value: "AG" },
    { id: 10, label: "Argentina", value: "AR" },
    { id: 11, label: "Armenia", value: "AM" },
    { id: 12, label: "Aruba", value: "AW" },
    { id: 13, label: "Australia", value: "AU" },
    { id: 14, label: "Austria", value: "AT" },
    { id: 15, label: "Azerbaijan", value: "AZ" },
    { id: 16, label: "Bahamas", value: "BS" },
    { id: 17, label: "Bahrain", value: "BH" },
    { id: 18, label: "Bangladesh", value: "BD" },
    { id: 19, label: "Barbados", value: "BB" },
    { id: 20, label: "Belarus", value: "BY" },
    { id: 21, label: "Belgium", value: "BE" },
    { id: 22, label: "Belize", value: "BZ" },
    { id: 23, label: "Benin", value: "BJ" },
    { id: 24, label: "Bermuda", value: "BM" },
    { id: 25, label: "Bhutan", value: "BT" },
    { id: 26, label: "Bolivia", value: "BO" },
    { id: 27, label: "Bosnia and Herzegovina", value: "BA" },
    { id: 28, label: "Botswana", value: "BW" },
    { id: 29, label: "Bouvet Island", value: "BV" },
    { id: 30, label: "Brazil", value: "BR" },
    { id: 31, label: "British Indian Ocean Territory", value: "IO" },
    { id: 32, label: "Brunei Darussalam", value: "BN" },
    { id: 33, label: "Bulgaria", value: "BG" },
    { id: 34, label: "Burkina Faso", value: "BF" },
    { id: 35, label: "Burundi", value: "BI" },
    { id: 36, label: "Cambodia", value: "KH" },
    { id: 37, label: "Cameroon", value: "CM" },
    { id: 38, label: "Canada", value: "CA" },
    { id: 39, label: "Cape Verde", value: "CV" },
    { id: 40, label: "Cayman Islands", value: "KY" },
    { id: 41, label: "Central African Republic", value: "CF" },
    { id: 42, label: "Chad", value: "TD" },
    { id: 43, label: "Chile", value: "CL" },
    { id: 44, label: "China", value: "CN" },
    { id: 45, label: "Christmas Island", value: "CX" },
    { id: 46, label: "Cocos (Keeling) Islands", value: "CC" },
    { id: 47, label: "Colombia", value: "CO" },
    { id: 48, label: "Comoros", value: "KM" },
    { id: 49, label: "Congo", value: "CG" },
    { id: 50, label: "Congo, The Democratic Republic of the", value: "CD" },
    { id: 51, label: "Cook Islands", value: "CK" },
    { id: 52, label: "Costa Rica", value: "CR" },
    { id: 53, label: "Cote D'Ivoire", value: "CI" },
    { id: 54, label: "Croatia", value: "HR" },
    { id: 55, label: "Cuba", value: "CU" },
    { id: 56, label: "Cyprus", value: "CY" },
    { id: 57, label: "Czech Republic", value: "CZ" },
    { id: 58, label: "Denmark", value: "DK" },
    { id: 59, label: "Djibouti", value: "DJ" },
    { id: 60, label: "Dominica", value: "DM" },
    { id: 61, label: "Dominican Republic", value: "DO" },
    { id: 62, label: "Ecuador", value: "EC" },
    { id: 63, label: "Egypt", value: "EG" },
    { id: 64, label: "El Salvador", value: "SV" },
    { id: 65, label: "Equatorial Guinea", value: "GQ" },
    { id: 66, label: "Eritrea", value: "ER" },
    { id: 67, label: "Estonia", value: "EE" },
    { id: 68, label: "Ethiopia", value: "ET" },
    { id: 69, label: "Falkland Islands (Malvinas)", value: "FK" },
    { id: 70, label: "Faroe Islands", value: "FO" },
    { id: 71, label: "Fiji", value: "FJ" },
    { id: 72, label: "Finland", value: "FI" },
    { id: 73, label: "France", value: "FR" },
    { id: 74, label: "French Guiana", value: "GF" },
    { id: 75, label: "French Polynesia", value: "PF" },
    { id: 76, label: "French Southern Territories", value: "TF" },
    { id: 77, label: "Gabon", value: "GA" },
    { id: 78, label: "Gambia", value: "GM" },
    { id: 79, label: "Georgia", value: "GE" },
    { id: 80, label: "Germany", value: "DE" },
    { id: 81, label: "Ghana", value: "GH" },
    { id: 82, label: "Gibraltar", value: "GI" },
    { id: 83, label: "Greece", value: "GR" },
    { id: 84, label: "Greenland", value: "GL" },
    { id: 85, label: "Grenada", value: "GD" },
    { id: 86, label: "Guadeloupe", value: "GP" },
    { id: 87, label: "Guam", value: "GU" },
    { id: 88, label: "Guatemala", value: "GT" },
    { id: 89, label: "Guinea", value: "GN" },
    { id: 90, label: "Guinea-Bissau", value: "GW" },
    { id: 91, label: "Guyana", value: "GY" },
    { id: 92, label: "Haiti", value: "HT" },
    { id: 93, label: "Heard Island and Mcdonald Islands", value: "HM" },
    { id: 94, label: "Holy See (Vatican City State)", value: "VA" },
    { id: 95, label: "Honduras", value: "HN" },
    { id: 96, label: "Hong Kong", value: "HK" },
    { id: 97, label: "Hungary", value: "HU" },
    { id: 98, label: "Iceland", value: "IS" },
    { id: 99, label: "India", value: "IN" },
    { id: 100, label: "Indonesia", value: "ID" },
    { id: 101, label: "Iran, Islamic Republic Of", value: "IR" },
    { id: 102, label: "Iraq", value: "IQ" },
    { id: 103, label: "Ireland", value: "IE" },
    { id: 104, label: "Isle of Man", value: "IM" },
    { id: 105, label: "Israel", value: "IL" },
    { id: 106, label: "Italy", value: "IT" },
    { id: 107, label: "Jamaica", value: "JM" },
    { id: 108, label: "Japan", value: "JP" },
    { id: 109, label: "Jersey", value: "JE" },
    { id: 110, label: "Jordan", value: "JO" },
    { id: 111, label: "Kazakhstan", value: "KZ" },
    { id: 112, label: "Kenya", value: "KE" },
    { id: 113, label: "Kiribati", value: "KI" },
    { id: 114, label: "Korea, Democratic People's Republic of", value: "KP" },
    { id: 115, label: "Kuwait", value: "KW" },
    { id: 116, label: "Kyrgyzstan", value: "KG" },
    { id: 117, label: "Lao People's Democratic Republic", value: "LA" },
    { id: 118, label: "Latvia", value: "LV" },
    { id: 119, label: "Lebanon", value: "LB" },
    { id: 120, label: "Lesotho", value: "LS" },
    { id: 121, label: "Liberia", value: "LR" },
    { id: 122, label: "Libya", value: "LY" },
    { id: 123, label: "Liechtenstein", value: "LI" },
    { id: 124, label: "Lithuania", value: "LT" },
    { id: 125, label: "Luxembourg", value: "LU" },
    { id: 126, label: "Macao", value: "MO" },
    { id: 127, label: "Madagascar", value: "MG" },
    { id: 128, label: "Malawi", value: "MW" },
    { id: 129, label: "Malaysia", value: "MY" },
    { id: 130, label: "Maldives", value: "MV" },
    { id: 131, label: "Mali", value: "ML" },
    { id: 132, label: "Malta", value: "MT" },
    { id: 133, label: "Marshall Islands", value: "MH" },
    { id: 134, label: "Martinique", value: "MQ" },
    { id: 135, label: "Mauritania", value: "MR" },
    { id: 136, label: "Mauritius", value: "MU" },
    { id: 137, label: "Mexico", value: "MX" },
    { id: 138, label: "Micronesia, Federated States of", value: "FM" },
    { id: 139, label: "Moldova, Republic of", value: "MD" },
    { id: 140, label: "Monaco", value: "MC" },
    { id: 141, label: "Mongolia", value: "MN" },
    { id: 142, label: "Montenegro", value: "ME" },
    { id: 143, label: "Montserrat", value: "MS" },
    { id: 144, label: "Morocco", value: "MA" },
    { id: 145, label: "Mozambique", value: "MZ" },
    { id: 146, label: "Myanmar", value: "MM" },
    { id: 147, label: "Namibia", value: "NA" },
    { id: 148, label: "Nauru", value: "NR" },
    { id: 149, label: "Nepal", value: "NP" },
    { id: 150, label: "Netherlands", value: "NL" },
    { id: 151, label: "New Zealand", value: "NZ" },
    { id: 152, label: "Nicaragua", value: "NI" },
    { id: 153, label: "Niger", value: "NE" },
    { id: 154, label: "Nigeria", value: "NG" },
    { id: 155, label: "Niue", value: "NU" },
    { id: 156, label: "Norfolk Island", value: "NF" },
    { id: 157, label: "Northern Mariana Islands", value: "MP" },
    { id: 158, label: "Norway", value: "NO" },
    { id: 159, label: "Oman", value: "OM" },
    { id: 160, label: "Pakistan", value: "PK" },
    { id: 161, label: "Palau", value: "PW" },
    { id: 162, label: "Palestinian Territory, Occupied", value: "PS" },
    { id: 163, label: "Panama", value: "PA" },
    { id: 164, label: "Papua New Guinea", value: "PG" },
    { id: 165, label: "Paraguay", value: "PY" },
    { id: 166, label: "Peru", value: "PE" },
    { id: 167, label: "Philippines", value: "PH" },
    { id: 168, label: "Poland", value: "PL" },
    { id: 169, label: "Portugal", value: "PT" },
    { id: 170, label: "Puerto Rico", value: "PR" },
    { id: 171, label: "Qatar", value: "QA" },
    { id: 172, label: "Romania", value: "RO" },
    { id: 173, label: "Russian Federation", value: "RU" },
    { id: 174, label: "Rwanda", value: "RW" },
    { id: 175, label: "Saint Barthélemy", value: "BL" },
    { id: 176, label: "Saint Kitts and Nevis", value: "KN" },
    { id: 177, label: "Saint Lucia", value: "LC" },
    { id: 178, label: "Saint Martin (French part)", value: "MF" },
    { id: 179, label: "Saint Vincent and the Grenadines", value: "VC" },
    { id: 180, label: "Samoa", value: "WS" },
    { id: 181, label: "San Marino", value: "SM" },
    { id: 182, label: "Sao Tome and Principe", value: "ST" },
    { id: 183, label: "Saudi Arabia", value: "SA" },
    { id: 184, label: "Senegal", value: "SN" },
    { id: 185, label: "Serbia", value: "RS" },
    { id: 186, label: "Seychelles", value: "SC" },
    { id: 187, label: "Sierra Leone", value: "SL" },
    { id: 188, label: "Singapore", value: "SG" },
    { id: 189, label: "Sint Maarten (Dutch part)", value: "SX" },
    { id: 190, label: "Slovakia", value: "SK" },
    { id: 191, label: "Slovenia", value: "SI" },
    { id: 192, label: "Solomon Islands", value: "SB" },
    { id: 193, label: "Somalia", value: "SO" },
    { id: 194, label: "South Africa", value: "ZA" },
    { id: 195, label: "South Korea", value: "KR" },
    { id: 196, label: "South Sudan", value: "SS" },
    { id: 197, label: "Spain", value: "ES" },
    { id: 198, label: "Sri Lanka", value: "LK" },
    { id: 199, label: "Sudan", value: "SD" },
    { id: 200, label: "Suriname", value: "SR" },
    { id: 201, label: "Swaziland", value: "SZ" },
    { id: 202, label: "Sweden", value: "SE" },
    { id: 203, label: "Switzerland", value: "CH" },
    { id: 204, label: "Syrian Arab Republic", value: "SY" },
    { id: 205, label: "Taiwan, Province of China", value: "TW" },
    { id: 206, label: "Tajikistan", value: "TJ" },
    { id: 207, label: "Tanzania, United Republic of", value: "TZ" },
    { id: 208, label: "Thailand", value: "TH" },
    { id: 209, label: "Timor-Leste", value: "TL" },
    { id: 210, label: "Togo", value: "TG" },
    { id: 211, label: "Tokelau", value: "TK" },
    { id: 212, label: "Tonga", value: "TO" },
    { id: 213, label: "Trinidad and Tobago", value: "TT" },
    { id: 214, label: "Tunisia", value: "TN" },
    { id: 215, label: "Turkey", value: "TR" },
    { id: 216, label: "Turkmenistan", value: "TM" },
    { id: 217, label: "Turks and Caicos Islands", value: "TC" },
    { id: 218, label: "Tuvalu", value: "TV" },
    { id: 219, label: "Uganda", value: "UG" },
    { id: 220, label: "Ukraine", value: "UA" },
    { id: 221, label: "United Arab Emirates", value: "AE" },
    { id: 222, label: "United Kingdom", value: "GB" },
    { id: 223, label: "United States", value: "US" },
    { id: 224, label: "Uruguay", value: "UY" },
    { id: 225, label: "Uzbekistan", value: "UZ" },
    { id: 226, label: "Vanuatu", value: "VU" },
    { id: 227, label: "Venezuela, Bolivarian Republic of", value: "VE" },
    { id: 228, label: "Vietnam", value: "VN" },
    { id: 229, label: "Virgin Islands, British", value: "VG" },
    { id: 230, label: "Virgin Islands, U.S.", value: "VI" },
    { id: 231, label: "Wallis and Futuna", value: "WF" },
    { id: 232, label: "Western Sahara", value: "EH" },
    { id: 233, label: "Yemen", value: "YE" },
    { id: 234, label: "Zambia", value: "ZM" },
    { id: 235, label: "Zimbabwe", value: "ZW" },
]
